collections:
  pages:
    output: true
    permalink: /:path/
  services:
    output: false

defaults:
  - scope:
      type: pages
    values:
      layout: default
      image: limes
  - scope:
      type: posts
    values:
      layout: post
      image: greenbeans

paginate: 5
paginate_path: /blog/page:num/
permalink: /blog/:year/:month/:day/:title
