features:
  - id: tips
    title: Premium Health<span class='break'></span>Resources and Tips
  - id: tracking
    title: "Diet Tracking<span class='break'></span><sub>w/ Fitbit Integration</sub>"
  - id: seasonal
    title: Seasonal<span class='break'></span>Meal Plans
  - id: tailored
    title: Personalized<span class='break'></span>Meal Planning
  - id: feedback
    title: Diet Tracking Review
  - id: mobile
    title: Mobile Chat<span class='break'></span>with Melissa
  - id: webinars
    title: Member Webinars
  - id: vision
    title: Vision and Goals Design
  - id: meet
    title: Meet with Melissa

collections:
  testimonials:
    output: false
  services:
    output: false
